name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt -t .
    - name: Create deployment package
      run: zip -r lambda_function_new.zip .
    - name: Deploy to Lambda
      uses: appleboy/lambda-action@v0.1.9
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        function_name: mongodb_backup_function
        zip_file: lambda_function_new.zip
        memory_size: 128
        timeout: 10
