name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt -t .
    - name: Create deployment package
      run: zip -r lambda_function_new.zip .
    - name: Deploy to Lambda
      uses: einaregilsson/aws-lambda-deploy@v1
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        function_name: mongodb_backup_function
        s3_bucket: mymongodbbackupsanjay
        filename: lambda_function_new.zip
